# Generated by Django 5.2 on 2026-03-08 13:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Activity', '0003_activity_attached_files'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_id', models.UUIDField(db_column='question_PK', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_description', models.TextField(db_column='question_description')),
                ('question_expected_result', models.FloatField(db_column='question_expected_result', default=0.0)),
                ('question_grade', models.FloatField(db_column='question_grade', default=0.0)),
                ('question_type', models.CharField(choices=[('MC', 'Multiple Choice'), ('UC', 'Unique Choice'), ('TF', 'True/False'), ('SA', 'Short Answer'), ('ES', 'Essay')], db_column='question_type', max_length=2)),
                ('question_response', models.JSONField(db_column='question_response', default=dict)),
                ('activity', models.ManyToManyField(db_column='question_activity_FK', related_name='questions', to='Activity.activity')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'db_table': 'Question',
            },
        ),
    ]
