# Generated by Django 5.2 on 2026-03-12 17:21

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Activity', '0007_remove_activity_submission_history_activity_and_more'),
        ('Question', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question_Submission',
            fields=[
                ('submission_id', models.UUIDField(db_column='submission_PK', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('submission_grade', models.FloatField(db_column='submission_grade', default=0.0)),
                ('teacher_feedback', models.TextField(db_column='teacher_feedback', default='')),
                ('submission', models.JSONField(db_column='submission_response', default=dict)),
                ('submitted_at', models.DateTimeField(auto_now_add=True, db_column='submission_submitted_at')),
                ('file', models.FileField(db_column='submission_file', upload_to='question_submissions/')),
                ('activity', models.ForeignKey(db_column='submission_activity_FK', on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='Activity.activity')),
                ('student', models.ForeignKey(db_column='submission_student_FK', on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL)),
                ('submission_question', models.ForeignKey(db_column='submission_question_FK', on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='Question.question')),
            ],
            options={
                'verbose_name': 'Question Submission',
                'verbose_name_plural': 'Question Submissions',
                'db_table': 'Question_Submission',
            },
        ),
        migrations.CreateModel(
            name='Question_Submission_History',
            fields=[
                ('submission_id', models.UUIDField(db_column='submission_PK', db_index=True, default=uuid.uuid4, editable=False)),
                ('submission_grade', models.FloatField(db_column='submission_grade', default=0.0)),
                ('teacher_feedback', models.TextField(db_column='teacher_feedback', default='')),
                ('submission', models.JSONField(db_column='submission_response', default=dict)),
                ('submitted_at', models.DateTimeField(blank=True, db_column='submission_submitted_at', editable=False)),
                ('file', models.TextField(db_column='submission_file', max_length=100)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('activity', models.ForeignKey(blank=True, db_column='submission_activity_FK', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Activity.activity')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(blank=True, db_column='submission_student_FK', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('submission_question', models.ForeignKey(blank=True, db_column='submission_question_FK', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Question.question')),
            ],
            options={
                'verbose_name': 'historical Question Submission',
                'verbose_name_plural': 'historical Question Submissions',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
