# Generated by Django 5.2 on 2026-03-12 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Question', '0002_question_submission_question_submission_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question_grade',
        ),
    ]
