# Generated by Django 5.2 on 2026-03-13 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Question', '0003_remove_question_question_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_options',
            field=models.JSONField(db_column='question_options', default=dict),
        ),
    ]
