# Generated by Django 5.2 on 2026-03-16 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Question', '0004_question_question_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question_submission_history',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='question_submission_history',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='question_submission_history',
            name='student',
        ),
        migrations.RemoveField(
            model_name='question_submission_history',
            name='submission_question',
        ),
        migrations.DeleteModel(
            name='Question_Submission',
        ),
        migrations.DeleteModel(
            name='Question_Submission_History',
        ),
    ]
