# Generated by Django 5.2 on 2026-03-16 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Question', '0005_remove_question_submission_history_activity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('MC', 'Multiple Choice'), ('UC', 'Unique Choice'), ('TF', 'True/False'), ('SA', 'Short Answer'), ('ES', 'Essay'), ('FL', 'File Upload')], db_column='question_type', max_length=2),
        ),
    ]
