# Generated by Django 5.2 on 2026-05-15 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Question', '0006_alter_question_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_order',
            field=models.IntegerField(db_column='question_order', default=0),
        ),
    ]
