services:
  db:
    image: postgres:15-alpine
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./Backend
    restart: always
    command: >
      sh -c "
      python manage.py migrate --noinput &&
      DJANGO_SUPERUSER_PASSWORD=$$SYS_PASSWORD DJANGO_SUPERUSER_NAME=$$SYS_NAME python manage.py createsuperuser --noinput --email $$SYS_EMAIL || true &&
      gunicorn ssa.wsgi:application --bind 0.0.0.0:8000 -w 5
      "
    env_file:
      - .env
    environment:
      - DB_HOST=db
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      - db
    volumes:
      - media_data:/app/media

  frontend:
    build: ./Frontend
    restart: always
    depends_on:
      - backend

  cloudflared:
    image: cloudflare/cloudflared:latest
    restart: always
    command: tunnel run
    env_file:
      - .env
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TOKEN}
    depends_on:
      - frontend
      - backend

volumes:
  postgres_data:
  media_data: