services:
  db:
    image: postgres:15-alpine
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - /opt/ssa/database:/var/lib/postgresql/data

  minio:
    image: minio/minio
    restart: always
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD}
    volumes:
      - /opt/ssa/minio_data:/data

  backend:
    build: ./Backend
    restart: always
    command: >
      sh -c "
      python manage.py migrate --noinput &&
      DJANGO_SUPERUSER_PASSWORD=$$SYS_PASSWORD DJANGO_SUPERUSER_NAME=$$SYS_NAME python manage.py createsuperuser --noinput --email $$SYS_EMAIL || true &&
      gunicorn ssa.wsgi:application --bind 0.0.0.0:8000 -w 5
      "
    env_file:
      - .env
    environment:
      - DB_HOST=db
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - AWS_ACCESS_KEY_ID=${MINIO_USER}
      - AWS_SECRET_ACCESS_KEY=${MINIO_PASSWORD}
      - AWS_STORAGE_BUCKET_NAME=${MINIO_BUCKET_NAME}
      - AWS_S3_ENDPOINT_URL=http://minio:9000
    depends_on:
      - db
      - minio

  frontend:
    build: ./FrontEnd
    restart: always
    depends_on:
      - backend

  cloudflared:
    image: cloudflare/cloudflared:latest
    restart: always
    command: tunnel run
    env_file:
      - .env
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TOKEN}
    depends_on:
      - frontend
      - backend