# Generated by Django 5.2 on 2026-06-08 14:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Course', '0005_rename_bimestre_course_bimester'),
        ('Question', '0007_question_question_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignGroup',
            fields=[
                ('campaign_id', models.UUIDField(db_column='campaign_PK', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='campaign_name', max_length=255)),
                ('description', models.TextField(blank=True, db_column='campaign_description', null=True)),
                ('is_active', models.BooleanField(db_column='campaign_is_active', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='campaign_created_at')),
            ],
            options={
                'verbose_name': 'Campaign Group',
                'verbose_name_plural': 'Campaign Groups',
                'db_table': 'Campaign_Group',
            },
        ),
        migrations.CreateModel(
            name='PracticeExam',
            fields=[
                ('exam_id', models.UUIDField(db_column='exam_PK', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='exam_name', max_length=255)),
                ('total_grade', models.FloatField(db_column='exam_total_grade', default=0.0)),
                ('to_be_launched', models.DateTimeField(db_column='exam_to_be_launched')),
                ('launched_at', models.DateTimeField(auto_now_add=True, db_column='exam_launched_at')),
                ('due_date', models.DateTimeField(db_column='exam_due_date')),
                ('description', models.TextField(db_column='exam_description')),
                ('is_active', models.BooleanField(db_column='exam_is_active', default=True)),
                ('status', models.CharField(choices=[('DRF', 'Draft'), ('PUB', 'Published')], db_column='exam_status', default='DRF', max_length=3)),
                ('campaign_group', models.ForeignKey(blank=True, db_column='exam_campaign_FK', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams', to='PracticeExam.campaigngroup')),
                ('course', models.ForeignKey(db_column='exam_course_FK', on_delete=django.db.models.deletion.CASCADE, related_name='practice_exams', to='Course.course')),
                ('questions', models.ManyToManyField(db_column='exam_question_FK', related_name='practice_exams', to='Question.question')),
            ],
            options={
                'verbose_name': 'Practice Exam',
                'verbose_name_plural': 'Practice Exams',
                'db_table': 'Practice_Exam',
            },
        ),
        migrations.CreateModel(
            name='AntiCheatLog',
            fields=[
                ('log_id', models.UUIDField(db_column='log_PK', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('left_at', models.DateTimeField(auto_now_add=True, db_column='log_left_at')),
                ('duration_seconds', models.FloatField(db_column='log_duration')),
                ('student', models.ForeignKey(db_column='log_student_FK', on_delete=django.db.models.deletion.CASCADE, related_name='anti_cheat_logs', to=settings.AUTH_USER_MODEL)),
                ('practice_exam', models.ForeignKey(db_column='log_exam_FK', on_delete=django.db.models.deletion.CASCADE, related_name='anti_cheat_logs', to='PracticeExam.practiceexam')),
            ],
            options={
                'verbose_name': 'Anti Cheat Log',
                'verbose_name_plural': 'Anti Cheat Logs',
                'db_table': 'Anti_Cheat_Log',
            },
        ),
        migrations.CreateModel(
            name='PracticeExam_Submission',
            fields=[
                ('submission_id', models.UUIDField(db_column='exam_submission_PK', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('submission_grade', models.FloatField(db_column='submission_grade', default=0.0)),
                ('submission', models.JSONField(db_column='submission_response', default=dict)),
                ('submitted_at', models.DateTimeField(auto_now_add=True, db_column='submission_submitted_at')),
                ('practice_exam', models.ForeignKey(db_column='submission_exam_FK', on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='PracticeExam.practiceexam')),
                ('student', models.ForeignKey(db_column='submission_student_FK', on_delete=django.db.models.deletion.CASCADE, related_name='exam_submissions', to=settings.AUTH_USER_MODEL)),
                ('submission_question', models.ForeignKey(db_column='submission_question_FK', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_submissions', to='Question.question')),
            ],
            options={
                'verbose_name': 'Practice Exam Submission',
                'verbose_name_plural': 'Practice Exam Submissions',
                'db_table': 'Practice_Exam_Submission',
            },
        ),
    ]
