# Generated by Django 5.2 on 2026-06-08 15:03

import apps.PracticeExam.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Activity', '0018_activity_campaign'),
        ('PracticeExam', '0002_campaignranking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anticheatlog',
            name='practice_exam',
        ),
        migrations.AddField(
            model_name='anticheatlog',
            name='submission',
            field=models.ForeignKey(db_column='log_submission_FK', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anti_cheat_logs', to='Activity.activity_submission'),
        ),
        migrations.AddField(
            model_name='campaigngroup',
            name='access_code',
            field=models.CharField(db_column='campaign_access_code', default=apps.PracticeExam.models.generate_access_code, max_length=10),
        ),
    ]
