# Generated by Django 5.2 on 2026-06-09 04:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PracticeExam', '0003_remove_anticheatlog_practice_exam_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaigngroup',
            name='is_active',
        ),
        migrations.AddField(
            model_name='campaigngroup',
            name='created_by',
            field=models.ForeignKey(db_column='campaign_created_by_FK', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaigns_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='campaigngroup',
            name='status',
            field=models.CharField(choices=[('ACT', 'Active'), ('INA', 'Inactive'), ('FIN', 'Finished')], db_column='campaign_status', default='ACT', max_length=3),
        ),
        migrations.AlterField(
            model_name='campaignranking',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
