# Generated by Django 5.2 on 2026-06-09 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PracticeExam', '0004_remove_campaigngroup_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='practiceexam',
            name='course',
        ),
    ]
