# Generated by Django 5.2 on 2026-03-04 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AuthUser', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='authuser',
            table='User',
        ),
    ]
