# Generated by Django 5.2 on 2026-03-04 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AuthUser', '0002_alter_authuser_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authuser',
            name='is_superuser',
        ),
    ]
