# Generated by Django 5.2 on 2026-03-19 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthUser', '0003_remove_authuser_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='authuser',
            name='image',
            field=models.ImageField(blank=True, db_column='user_image', null=True, upload_to='user_images/'),
        ),
    ]
