# Generated by Django 5.2 on 2026-03-05 00:03

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Course', '0002_alter_course_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('activity_id', models.UUIDField(db_column='activity_PK', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='activity_name', max_length=255)),
                ('total_grade', models.FloatField(db_column='activity_total_grade')),
                ('has_submission', models.BooleanField(db_column='activity_has_submission', default=True)),
                ('to_be_launched', models.DateTimeField(db_column='to_be_launched')),
                ('lauched_at', models.DateTimeField(db_column='activity_lauched_at', default=datetime.datetime(2026, 3, 5, 0, 3, 26, 989594, tzinfo=datetime.timezone.utc))),
                ('due_date', models.DateTimeField(db_column='activity_due_date')),
                ('description', models.TextField(db_column='activity_description')),
                ('is_active', models.BooleanField(db_column='activity_is_active', default=True)),
                ('course', models.ForeignKey(db_column='activity_course_FK', on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='Course.course')),
            ],
            options={
                'verbose_name': 'Activity',
                'verbose_name_plural': 'Activities',
                'db_table': 'Activity',
            },
        ),
    ]
