# Generated by Django 5.2 on 2026-03-05 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Activity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='lauched_at',
            field=models.DateTimeField(auto_now_add=True, db_column='activity_lauched_at'),
        ),
    ]
