# Generated by Django 5.2 on 2026-03-05 01:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Activity', '0002_alter_activity_lauched_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity_Attached_Files',
            fields=[
                ('attached_files_id', models.UUIDField(db_column='attached_files_PK', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(db_column='file', upload_to='activity_files/')),
                ('activity', models.ForeignKey(db_column='attached_files_activity_FK', on_delete=django.db.models.deletion.CASCADE, related_name='attached_files', to='Activity.activity')),
            ],
            options={
                'verbose_name': 'Attached File',
                'verbose_name_plural': 'Attached Files',
                'db_table': 'Attached_Files',
            },
        ),
    ]
