# Generated by Django 5.2 on 2026-03-12 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Activity', '0003_activity_attached_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('ATV', 'Activity'), ('LAB', 'Lab'), ('PRJ', 'Project'), ('TST', 'Test')], db_column='activity_type', default='ATV', max_length=3),
        ),
    ]
