# Generated by Django 5.2 on 2026-03-12 17:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Activity', '0005_activity_submission_historicalactivity_submission'),
        ('Question', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HistoricalActivity_Submission',
            new_name='Activity_Submission_History',
        ),
    ]
