# Generated by Django 5.2 on 2026-03-12 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Activity', '0006_rename_historicalactivity_submission_activity_submission_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity_submission_history',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='activity_submission_history',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='activity_submission_history',
            name='student',
        ),
        migrations.RemoveField(
            model_name='activity_submission_history',
            name='submission_question',
        ),
        migrations.DeleteModel(
            name='Activity_Submission',
        ),
        migrations.DeleteModel(
            name='Activity_Submission_History',
        ),
    ]
