# Generated by Django 5.2 on 2026-03-13 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Activity', '0007_remove_activity_submission_history_activity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='status',
            field=models.CharField(choices=[('DRF', 'Draft'), ('PUB', 'Published')], db_column='activity_status', default='DRF', max_length=3),
        ),
    ]
