# Generated by Django 5.2 on 2026-03-17 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Activity', '0009_activity_submission_activity_submission_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity_submission',
            name='submission_question',
        ),
        migrations.RemoveField(
            model_name='activity_submission_history',
            name='submission_question',
        ),
    ]
