# Generated by Django 5.2 on 2026-03-17 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Activity', '0010_remove_activity_submission_submission_question_and_more'),
        ('Question', '0006_alter_question_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity_submission',
            name='question',
            field=models.ForeignKey(db_column='submission_question_FK', default=None, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='Question.question'),
        ),
        migrations.AddField(
            model_name='activity_submission_history',
            name='question',
            field=models.ForeignKey(blank=True, db_column='submission_question_FK', db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Question.question'),
        ),
    ]
