# Generated by Django 5.2 on 2026-03-17 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Activity', '0011_activity_submission_question_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity_submission',
            old_name='question',
            new_name='submission_question',
        ),
        migrations.RenameField(
            model_name='activity_submission_history',
            old_name='question',
            new_name='submission_question',
        ),
    ]
