# Generated by Django 5.2 on 2026-03-18 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Activity', '0012_rename_question_activity_submission_submission_question_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity_submission',
            name='teacher_feedback',
            field=models.TextField(blank=True, db_column='teacher_feedback', default=''),
        ),
        migrations.AlterField(
            model_name='activity_submission_history',
            name='teacher_feedback',
            field=models.TextField(blank=True, db_column='teacher_feedback', default=''),
        ),
    ]
