# Generated by Django 5.2 on 2026-03-18 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Activity', '0013_alter_activity_submission_teacher_feedback_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity_submission',
            name='has_teacher_revision',
            field=models.BooleanField(db_column='has_teacher_reviision', default=False),
        ),
        migrations.AddField(
            model_name='activity_submission_history',
            name='has_teacher_revision',
            field=models.BooleanField(db_column='has_teacher_reviision', default=False),
        ),
    ]
