# Generated by Django 5.2 on 2026-04-13 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Activity', '0014_activity_submission_has_teacher_revision_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('ATV', 'Activity'), ('LAB', 'Lab'), ('PRJ', 'Project'), ('TST', 'Test'), ('FIL', 'File')], db_column='activity_type', default='ATV', max_length=3),
        ),
    ]
