# Generated by Django 5.2 on 2026-05-14 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Activity', '0015_alter_activity_activity_type'),
        ('Question', '0006_alter_question_question_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity_submission',
            name='submission_question',
            field=models.ForeignKey(db_column='submission_question_FK', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='Question.question'),
        ),
    ]
