# Generated by Django 5.2 on 2026-06-08 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Activity', '0016_alter_activity_submission_submission_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('ATV', 'Activity'), ('LAB', 'Lab'), ('PRJ', 'Project'), ('TST', 'Test'), ('FIL', 'File'), ('SIM', 'Simulado')], db_column='activity_type', default='ATV', max_length=3),
        ),
    ]
