# Generated by Django 5.2 on 2026-06-08 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Activity', '0017_alter_activity_activity_type'),
        ('PracticeExam', '0002_campaignranking'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='campaign',
            field=models.ForeignKey(blank=True, db_column='activity_campaign_FK', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='PracticeExam.campaigngroup'),
        ),
    ]
