# Generated by Django 5.2 on 2026-03-04 23:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('course_name', models.CharField(db_column='course_name', max_length=255)),
                ('course_year', models.IntegerField(db_column='course_year')),
                ('is_active', models.BooleanField(db_column='is_active', default=True)),
                ('color', models.CharField(db_column='color', max_length=7)),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'db_table': 'Course',
                'ordering': ['course_year'],
            },
        ),
    ]
