# Generated by Django 5.2 on 2026-03-04 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='color',
            field=models.CharField(db_column='color', default='#000000', max_length=7),
        ),
    ]
