# Generated by Django 5.2 on 2026-03-05 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0002_alter_course_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='id',
            new_name='course_id',
        ),
    ]
