# Generated by Django 5.2 on 2026-05-18 12:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0003_rename_id_course_course_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bimestre',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=255)),
                ('year', models.IntegerField(db_column='year')),
            ],
            options={
                'verbose_name': 'Bimestre',
                'verbose_name_plural': 'Bimestres',
                'db_table': 'Bimestre',
                'ordering': ['-year', 'name'],
            },
        ),
        migrations.AddField(
            model_name='course',
            name='bimestre',
            field=models.ForeignKey(blank=True, db_column='bimestre_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='Course.bimestre'),
        ),
    ]
