# Generated by Django 5.2 on 2026-05-18 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0004_bimestre_course_bimestre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='bimestre',
            new_name='bimester',
        ),
    ]
